//
// Sound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SoundList: Codable {
    
    public var count: Int
    
    public var results: [Sound]
    
    public var next: String?
    
    public var prev: String?
    
    public init(count: Int, results: [Sound], next: String?, prev: String?) {
        self.count = count
        self.results = results
        self.next = next
        self.prev = prev
    }
    
    public enum CodingKeys: String, CodingKey {
        case count = "count"
        case results = "results"
        case next = "next"
        case prev = "prev"
    }
}

public struct Sound: Codable {

    /** The soundâ€™s unique identifier. */
    public var identifier: Int64?
    /** The name user gave to the sound. */
    public var name: String?
    /** The URI for this sound on the Freesound website. */
    public var url: String?
    
    public var desc: String?
    
    public var duration: Float?
    
    public var downloads: Int64?
    
    public var rating: Float?
    
    public var previews: [String : String]?
    
    public var images: [String : String]?

    public init(id: Int64?,
                name: String?,
                url: String?,
                desc: String?,
                duration: Float?,
                downloads: Int64?,
                rating: Float?,
                previews: [String : String]?,
                images: [String : String]?) {
        self.identifier = id
        self.name = name
        self.url = url
        self.desc = desc
        self.duration = duration
        self.downloads = downloads
        self.rating = rating
        self.previews = previews
        self.images = images
    }

    public enum CodingKeys: String, CodingKey { 
        case identifier = "id"
        case name = "name"
        case url = "url"
        case desc = "description"
        case duration = "duration"
        case downloads = "num_downloads"
        case rating = "avg_rating"
        case previews = "previews"
        case images = "images"
    }


}


extension Sound: Identifiable {
    public var id: String { "\(String(describing: identifier))" }
}
