//
// SearchAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SearchAPI {
    /**
     * enum for parameter sort
     */
    public enum Sort_searchText: String { 
        case score = "score"
        case durationDesc = "duration_desc"
        case durationAsc = "duration_asc"
        case createdDesc = "created_desc"
        case createdAsc = "created_asc"
        case downloadsDesc = "downloads_desc"
        case downloadsAsc = "downloads_asc"
        case ratingDesc = "rating_desc"
        case ratingAsc = "rating_asc"
    }

    /**
     Search sounds
     
     - parameter query: (query) The query! The query is the main parameter used to define a query. You can type several terms separated by spaces or phrases wrapped inside quote â€˜â€â€™ characters. For every term, you can also use â€˜+â€™ and â€˜-â€˜ modifier characters to indicate that a term is â€œmandatoryâ€ or â€œprohibitedâ€ (by default, terms are considered to be â€œmandatoryâ€). For example, in a query such as query&#x3D;term_a -term_b, sounds including term_b will not match the search criteria. The query does a weighted search over some sound properties including sound tags, the sound name, its description, pack name and the sound id. Therefore, searching for query&#x3D;123 will find you sounds with id 1234, sounds that have 1234 in the description, in the tags, etc. Youâ€™ll find some examples below. Using an empty query (query&#x3D; or query&#x3D;\&quot;\&quot;) will return all Freeosund sounds. (optional)
     - parameter filter: (query) Allows filtering query results. See below for more information. (optional)
     - parameter sort: (query) Indicates how query results should be sorted. See below for a list of the sorting options. By default &#x60;sort&#x3D;score&#x60;. &lt;p&gt; &lt;table&gt;   &lt;tr&gt;     &lt;th&gt;Option&lt;/th&gt;     &lt;th&gt;Explanation&lt;/th&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;score&lt;/td&gt;     &lt;td&gt;Sort by a relevance score returned by our search engine (default).&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;duration_desc     &lt;td&gt;Sort by the duration of the sounds, longest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;duration_asc     &lt;td&gt;Same as above, but shortest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;created_desc     &lt;td&gt;Sort by the date of when the sound was added. newest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;created_asc     &lt;td&gt;Same as above, but oldest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;downloads_desc     &lt;td&gt;Sort by the number of downloads, most downloaded sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;downloads_asc     &lt;td&gt;Same as above, but least downloaded sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;rating_desc     &lt;td&gt;Sort by the average rating given to the sounds, highest rated first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;rating_asc     &lt;td&gt;Same as above, but lowest rated sounds first.   &lt;/tr&gt; &lt;/table&gt; &lt;/p&gt; (optional)
     - parameter groupByPack: (query) This parameter represents a boolean option to indicate whether to collapse results belonging to sounds of the same pack into single entries in the results list. If &#x60;group_by_pack&#x3D;1&#x60; and search results contain more than one sound that belongs to the same pack, only one sound for each distinct pack is returned (sounds with no packs are returned as well). However, the returned sound will feature two extra properties to access these other sounds omitted from the results list: &#x60;n_from_same_pack&#x60;: indicates how many other results belong to the same pack (and have not been returned) &#x60;more_from_same_pack&#x60;: uri pointing to the list of omitted sound results of the same pack (also including the result which has already been returned). See examples below. By default &#x60;group_by_pack&#x3D;0&#x60;. (optional)
     - parameter page: (query) Query results are paginated, this parameter indicates what page should be returned. By default &#x60;page&#x3D;1&#x60;. (optional, default to 1)
     - parameter pageSize: (query) Indicates the number of sounds per page to include in the result. By default &#x60;page_size&#x3D;15&#x60;, and the maximum is &#x60;page_size&#x3D;150&#x60;. Not that with bigger &#x60;page_size&#x60;, more data will need to be transferred. (optional, default to 15)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchText(query: String? = nil, filter: String? = nil, sort: Sort_searchText? = nil, groupByPack: Int? = nil, page: Int? = nil, pageSize: Int? = nil, completion: @escaping ((_ data: SoundList?,_ error: Error?) -> Void)) {
        searchTextWithRequestBuilder(query: query, filter: filter, sort: sort, groupByPack: groupByPack, page: page, pageSize: pageSize).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search sounds
     - GET /search/text
     - This resource allows searching sounds in Freesound by matching their tags and other kinds of metadata.
     - examples: [{contentType=application/xml, example=<null>
  <id>123456789</id>
  <name>aeiou</name>
  <url>aeiou</url>
</null>}, {contentType=application/json, example=[ {
  "name" : "name",
  "id" : 0,
  "url" : "url"
}, {
  "name" : "name",
  "id" : 0,
  "url" : "url"
} ]}]
     - examples: [{contentType=application/xml, example=<null>
  <id>123456789</id>
  <name>aeiou</name>
  <url>aeiou</url>
</null>}, {contentType=application/json, example=[ {
  "name" : "name",
  "id" : 0,
  "url" : "url"
}, {
  "name" : "name",
  "id" : 0,
  "url" : "url"
} ]}]
     
     - parameter query: (query) The query! The query is the main parameter used to define a query. You can type several terms separated by spaces or phrases wrapped inside quote â€˜â€â€™ characters. For every term, you can also use â€˜+â€™ and â€˜-â€˜ modifier characters to indicate that a term is â€œmandatoryâ€ or â€œprohibitedâ€ (by default, terms are considered to be â€œmandatoryâ€). For example, in a query such as query&#x3D;term_a -term_b, sounds including term_b will not match the search criteria. The query does a weighted search over some sound properties including sound tags, the sound name, its description, pack name and the sound id. Therefore, searching for query&#x3D;123 will find you sounds with id 1234, sounds that have 1234 in the description, in the tags, etc. Youâ€™ll find some examples below. Using an empty query (query&#x3D; or query&#x3D;\&quot;\&quot;) will return all Freeosund sounds. (optional)
     - parameter filter: (query) Allows filtering query results. See below for more information. (optional)
     - parameter sort: (query) Indicates how query results should be sorted. See below for a list of the sorting options. By default &#x60;sort&#x3D;score&#x60;. &lt;p&gt; &lt;table&gt;   &lt;tr&gt;     &lt;th&gt;Option&lt;/th&gt;     &lt;th&gt;Explanation&lt;/th&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;score&lt;/td&gt;     &lt;td&gt;Sort by a relevance score returned by our search engine (default).&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;duration_desc     &lt;td&gt;Sort by the duration of the sounds, longest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;duration_asc     &lt;td&gt;Same as above, but shortest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;created_desc     &lt;td&gt;Sort by the date of when the sound was added. newest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;created_asc     &lt;td&gt;Same as above, but oldest sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;downloads_desc     &lt;td&gt;Sort by the number of downloads, most downloaded sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;downloads_asc     &lt;td&gt;Same as above, but least downloaded sounds first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;rating_desc     &lt;td&gt;Sort by the average rating given to the sounds, highest rated first.   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;rating_asc     &lt;td&gt;Same as above, but lowest rated sounds first.   &lt;/tr&gt; &lt;/table&gt; &lt;/p&gt; (optional)
     - parameter groupByPack: (query) This parameter represents a boolean option to indicate whether to collapse results belonging to sounds of the same pack into single entries in the results list. If &#x60;group_by_pack&#x3D;1&#x60; and search results contain more than one sound that belongs to the same pack, only one sound for each distinct pack is returned (sounds with no packs are returned as well). However, the returned sound will feature two extra properties to access these other sounds omitted from the results list: &#x60;n_from_same_pack&#x60;: indicates how many other results belong to the same pack (and have not been returned) &#x60;more_from_same_pack&#x60;: uri pointing to the list of omitted sound results of the same pack (also including the result which has already been returned). See examples below. By default &#x60;group_by_pack&#x3D;0&#x60;. (optional)
     - parameter page: (query) Query results are paginated, this parameter indicates what page should be returned. By default &#x60;page&#x3D;1&#x60;. (optional, default to 1)
     - parameter pageSize: (query) Indicates the number of sounds per page to include in the result. By default &#x60;page_size&#x3D;15&#x60;, and the maximum is &#x60;page_size&#x3D;150&#x60;. Not that with bigger &#x60;page_size&#x60;, more data will need to be transferred. (optional, default to 15)

     - returns: RequestBuilder<SoundList>
     */
    open class func searchTextWithRequestBuilder(query: String? = nil, filter: String? = nil, sort: Sort_searchText? = nil, groupByPack: Int? = nil, page: Int? = nil, pageSize: Int? = nil) -> RequestBuilder<SoundList> {
        let path = "/search/text/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": query, 
            "filter": filter, 
            "sort": sort?.rawValue, 
            "group_by_pack": groupByPack?.encodeToJSON(), 
            "page": page?.encodeToJSON(), 
            "page_size": pageSize?.encodeToJSON(),
            "token": "f90ZvCwTwPxBOewsaE6fw9BZRALYpw5986bAXOn0"
        ])

        let requestBuilder: RequestBuilder<SoundList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
